spring:
  application:
    name: payment-service

grpc:
  server:
    port: 9091
    security:
      enabled: true
      certificateChain: file:/etc/certs/payment.crt
      privateKey: file:/etc/certs/payment.key
      trustCertCollection: file:/etc/certs/ca.crt
      clientAuth: REQUIRE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
