spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

grpc:
  client:
    inventoryService:
      address: inventory-service
      port: 9090
#      negotiationType: TLS
#      security:
#        certificateChain: ${GRPC_CLIENT_CERT_CHAIN}
#        privateKey: ${GRPC_CLIENT_PRIVATE_KEY}
#        trustCertCollection: ${GRPC_TRUST_CERT_COLLECTION}
#
    paymentService:
      address: payment-service
      port: 9091
#      negotiationType: TLS
#      security:
#        trustCertCollection: ${GRPC_TRUST_CERT_COLLECTION}
#        certificateChain: ${GRPC_CLIENT_CERT_CHAIN}
#        clientPrivateKey: ${GRPC_CLIENT_PRIVATE_KEY}
certs:
  certificateChain: ${GRPC_CLIENT_CERT_CHAIN}
  privateKey: ${GRPC_CLIENT_PRIVATE_KEY}
  trustCertCollection: ${GRPC_TRUST_CERT_COLLECTION}

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      paymentService:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s

  retry:
    instances:
      inventoryService:
        maxAttempts: 3
        waitDuration: 500ms
      paymentService:
        maxAttempts: 2
        waitDuration: 500ms

  timelimiter:
    instances:
      inventoryService:
        timeoutDuration: 2s
      paymentService:
        timeoutDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
#    io.grpc.netty: DEBUG
#    io.netty.handler.ssl: DEBUG
#    io.grpc: DEBUG
    net.devh.boot.grpc.client: DEBUG

